package me.khrystal.gmatorm.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import me.khrystal.gmatorm.ormdto.VocabularyDeckFlashcard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VocabularyDeckFlashcard".
*/
public class VocabularyDeckFlashcardDao extends AbstractDao<VocabularyDeckFlashcard, Long> {

    public static final String TABLENAME = "VocabularyDeckFlashcard";

    /**
     * Properties of entity VocabularyDeckFlashcard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IsNew = new Property(1, boolean.class, "isNew", false, "is_new");
        public final static Property Creation_date = new Property(2, String.class, "creation_date", false, "creation_date");
        public final static Property Modified_data = new Property(3, String.class, "modified_data", false, "modified_data");
        public final static Property Create_at = new Property(4, String.class, "create_at", false, "created_at");
        public final static Property Updated_at = new Property(5, String.class, "updated_at", false, "updated_at");
        public final static Property Client_creation_date = new Property(6, String.class, "client_creation_date", false, "client_creation_date");
        public final static Property Uuid = new Property(7, String.class, "uuid", false, "uuid");
        public final static Property Order = new Property(8, String.class, "order", false, "order");
        public final static Property Deck_id = new Property(9, Long.class, "deck_id", false, "deck_id");
        public final static Property Flashcard_id = new Property(10, Long.class, "flashcard_id", false, "flashcard_id");
    }


    public VocabularyDeckFlashcardDao(DaoConfig config) {
        super(config);
    }
    
    public VocabularyDeckFlashcardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VocabularyDeckFlashcard entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIsNew() ? 1L: 0L);
 
        String creation_date = entity.getCreation_date();
        if (creation_date != null) {
            stmt.bindString(3, creation_date);
        }
 
        String modified_data = entity.getModified_data();
        if (modified_data != null) {
            stmt.bindString(4, modified_data);
        }
 
        String create_at = entity.getCreate_at();
        if (create_at != null) {
            stmt.bindString(5, create_at);
        }
 
        String updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindString(6, updated_at);
        }
 
        String client_creation_date = entity.getClient_creation_date();
        if (client_creation_date != null) {
            stmt.bindString(7, client_creation_date);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(8, uuid);
        }
 
        String order = entity.getOrder();
        if (order != null) {
            stmt.bindString(9, order);
        }
 
        Long deck_id = entity.getDeck_id();
        if (deck_id != null) {
            stmt.bindLong(10, deck_id);
        }
 
        Long flashcard_id = entity.getFlashcard_id();
        if (flashcard_id != null) {
            stmt.bindLong(11, flashcard_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VocabularyDeckFlashcard entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIsNew() ? 1L: 0L);
 
        String creation_date = entity.getCreation_date();
        if (creation_date != null) {
            stmt.bindString(3, creation_date);
        }
 
        String modified_data = entity.getModified_data();
        if (modified_data != null) {
            stmt.bindString(4, modified_data);
        }
 
        String create_at = entity.getCreate_at();
        if (create_at != null) {
            stmt.bindString(5, create_at);
        }
 
        String updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindString(6, updated_at);
        }
 
        String client_creation_date = entity.getClient_creation_date();
        if (client_creation_date != null) {
            stmt.bindString(7, client_creation_date);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(8, uuid);
        }
 
        String order = entity.getOrder();
        if (order != null) {
            stmt.bindString(9, order);
        }
 
        Long deck_id = entity.getDeck_id();
        if (deck_id != null) {
            stmt.bindLong(10, deck_id);
        }
 
        Long flashcard_id = entity.getFlashcard_id();
        if (flashcard_id != null) {
            stmt.bindLong(11, flashcard_id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VocabularyDeckFlashcard readEntity(Cursor cursor, int offset) {
        VocabularyDeckFlashcard entity = new VocabularyDeckFlashcard( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getShort(offset + 1) != 0, // isNew
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // creation_date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // modified_data
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // create_at
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // updated_at
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // client_creation_date
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // uuid
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // order
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // deck_id
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // flashcard_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VocabularyDeckFlashcard entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsNew(cursor.getShort(offset + 1) != 0);
        entity.setCreation_date(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setModified_data(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreate_at(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUpdated_at(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setClient_creation_date(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUuid(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setOrder(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDeck_id(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setFlashcard_id(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VocabularyDeckFlashcard entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VocabularyDeckFlashcard entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VocabularyDeckFlashcard entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
