package me.khrystal.gmatorm.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import me.khrystal.gmatorm.ormdto.VocabularyCategory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "vocabularycategory".
*/
public class VocabularyCategoryDao extends AbstractDao<VocabularyCategory, Long> {

    public static final String TABLENAME = "vocabularycategory";

    /**
     * Properties of entity VocabularyCategory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property IsNew = new Property(1, boolean.class, "isNew", false, "is_new");
        public final static Property Creation_date = new Property(2, String.class, "creation_date", false, "creation_date");
        public final static Property Modified_data = new Property(3, String.class, "modified_data", false, "modified_data");
        public final static Property Create_at = new Property(4, String.class, "create_at", false, "created_at");
        public final static Property Updated_at = new Property(5, String.class, "updated_at", false, "updated_at");
        public final static Property Client_creation_date = new Property(6, String.class, "client_creation_date", false, "client_creation_date");
        public final static Property Title = new Property(7, String.class, "title", false, "title");
        public final static Property Resource_uri = new Property(8, String.class, "resource_uri", false, "resource_uri");
        public final static Property Order = new Property(9, int.class, "order", false, "order");
        public final static Property Uuid = new Property(10, String.class, "uuid", false, "uuid");
        public final static Property Is_active = new Property(11, boolean.class, "is_active", false, "is_active");
    }


    public VocabularyCategoryDao(DaoConfig config) {
        super(config);
    }
    
    public VocabularyCategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VocabularyCategory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIsNew() ? 1L: 0L);
 
        String creation_date = entity.getCreation_date();
        if (creation_date != null) {
            stmt.bindString(3, creation_date);
        }
 
        String modified_data = entity.getModified_data();
        if (modified_data != null) {
            stmt.bindString(4, modified_data);
        }
 
        String create_at = entity.getCreate_at();
        if (create_at != null) {
            stmt.bindString(5, create_at);
        }
 
        String updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindString(6, updated_at);
        }
 
        String client_creation_date = entity.getClient_creation_date();
        if (client_creation_date != null) {
            stmt.bindString(7, client_creation_date);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
 
        String resource_uri = entity.getResource_uri();
        if (resource_uri != null) {
            stmt.bindString(9, resource_uri);
        }
        stmt.bindLong(10, entity.getOrder());
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(11, uuid);
        }
        stmt.bindLong(12, entity.getIs_active() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VocabularyCategory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIsNew() ? 1L: 0L);
 
        String creation_date = entity.getCreation_date();
        if (creation_date != null) {
            stmt.bindString(3, creation_date);
        }
 
        String modified_data = entity.getModified_data();
        if (modified_data != null) {
            stmt.bindString(4, modified_data);
        }
 
        String create_at = entity.getCreate_at();
        if (create_at != null) {
            stmt.bindString(5, create_at);
        }
 
        String updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindString(6, updated_at);
        }
 
        String client_creation_date = entity.getClient_creation_date();
        if (client_creation_date != null) {
            stmt.bindString(7, client_creation_date);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
 
        String resource_uri = entity.getResource_uri();
        if (resource_uri != null) {
            stmt.bindString(9, resource_uri);
        }
        stmt.bindLong(10, entity.getOrder());
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(11, uuid);
        }
        stmt.bindLong(12, entity.getIs_active() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VocabularyCategory readEntity(Cursor cursor, int offset) {
        VocabularyCategory entity = new VocabularyCategory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getShort(offset + 1) != 0, // isNew
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // creation_date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // modified_data
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // create_at
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // updated_at
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // client_creation_date
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // title
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // resource_uri
            cursor.getInt(offset + 9), // order
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // uuid
            cursor.getShort(offset + 11) != 0 // is_active
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VocabularyCategory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsNew(cursor.getShort(offset + 1) != 0);
        entity.setCreation_date(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setModified_data(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreate_at(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUpdated_at(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setClient_creation_date(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTitle(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setResource_uri(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setOrder(cursor.getInt(offset + 9));
        entity.setUuid(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setIs_active(cursor.getShort(offset + 11) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VocabularyCategory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VocabularyCategory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VocabularyCategory entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
