/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_khrystal_gifbuilder_encoder_GIFEncoder */

#ifndef _Included_me_khrystal_gifbuilder_encoder_GIFEncoder
#define _Included_me_khrystal_gifbuilder_encoder_GIFEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_khrystal_gifbuilder_encoder_GIFEncoder
 * Method:    getImagePixelsNative
 * Signature: (Ljava/lang/Object;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_me_khrystal_gifbuilder_encoder_GIFEncoder_getImagePixelsNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
